config/routes.rb
Rails.application.routes.draw do
  scope module: :public do
    root to: 'homes#top'
    resource :users, only:[:show, :edit, :update]
      get 'users/confirm' => 'users#confirm', as: 'users_confirm'
      patch 'users/cancellation' => 'users#cancellation', as: 'users_cancellation'
    resources :addresses, :except =>[:show, :new]
    resources :shops
    get 'shop/store' => 'shops#store', as: 'shops_store'
    resources :items do
      resource :likes, only: [:create, :destroy]
    end
    resources :cart_items, :except => [:show, :new, :edit]
      delete 'cart_item/destroy_all' => 'cart_items#destroy_all'
    resources :orders, :except =>[:update, :destroy, :edit, :index, :show]
      post 'orders/confirm' => 'orders#confirm', as: 'orders_confirm'
  end

  namespace :admin do
    resources :shop_genres, :except => [:show, :new]
    resources :item_genres, :except => [:show, :new]
  end

  devise_for :admins
  devise_for :users
end

app/models/address.rb
class Address < ApplicationRecord
  validates :name, :address, presence: true
  validates :postal_code, length: { is: 7 }, numericality: { only_integer: true }

  belongs_to :user
  def full_address
    "〒" + self.postal_code.to_s.insert(3, "-") + self.address + "　" + self.name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :user
  belongs_to :item
  validates :amount, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  attachment :image
  validates :name, :introduction, :image, :price, :stock, presence: true
  belongs_to :shop
  belongs_to :item_genre
  has_many :likes, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :order_items, dependent: :destroy

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end
end

app/models/item_genre.rb
class ItemGenre < ApplicationRecord
  belongs_to :shop_genre
  has_many :items, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :item
  validates_uniqueness_of :item_id, scope: :user_id
end

app/models/order.rb
class Order < ApplicationRecord

  validates :postal_code, length: { is: 7 }, numericality: { only_integer: true }
  validates :name, :address, presence: true
  belongs_to :user
  has_many :order_items, dependent: :destroy
   enum payment_method: [
    "Credit Card","Bank Transfer"
   ]

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/models/shop.rb
class Shop < ApplicationRecord
  attachment :image

  validates :name, :introduction, presence: true, length: { maximum: 200 }
  validates :user_id, uniqueness: true

  belongs_to :user
  belongs_to :shop_genre
  has_many :items, dependent: :destroy

  enum prefectures: {
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47
  }
end

app/models/shop_genre.rb
class ShopGenre < ApplicationRecord
    validates :name, presence: true, uniqueness: true
    has_many :shops, dependent: :destroy
    has_many :item_genres, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable

  def already_liked?(item)
    self.likes.exists?(item_id: item.id)
  end

  def active_for_authentication?
    super && (self.is_active == true)
  end

  attachment :image
  validates :name, :name_kana, :nickname, :address, presence: true
  validates :name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
  validates :postal_code, length: { is: 7 }
  validates :telephone_number, length: { is: 11 }
  validates :postal_code, :telephone_number, numericality: { only_integer: true }
  validates :email, presence: true, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i}

  with_options on: :create do |create|
    create.validates :password, presence: true, on: :create
    create.validates :password, confirmation: true, on: :create
    create.validates :password_confirmation, presence: true, on: :create
  end
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_items, through: :likes, source: :item
  has_one :shop
end

app/controllers/admin/item_genres_controller.rb
class Admin::ItemGenresController < ApplicationController
  def index
    @item_genre = ItemGenre.new
    @item_genres = ItemGenre.page(params[:page]).reverse_order
    @shop_genres = ShopGenre.all
  end

  def create
    @item_genre = ItemGenre.new(item_genre_params)
    if @item_genre.save
      redirect_to admin_item_genres_path
    else
      @item_genres = ItemGenre.all
      @shop_genres = ShopGenre.all
      render :index
    end
  end

  def edit
    @item_genre = ItemGenre.find(params[:id])
  end

  def update
    @item_genre = ItemGenre.find(params[:id])
    if @item_genre.update(item_genre_params)
      redirect_to admin_item_genres_path
    else
      render :edit
    end
  end

  def destroy
    @item_genre = ItemGenre.find(params[:id])
    @item_genre.delete
    redirect_to admin_item_genres_path
  end

  private

  def item_genre_params
    params.require(:item_genre).permit(:shop_genre_id, :name)
  end
end

app/controllers/admin/shop_genres_controller.rb
class Admin::ShopGenresController < ApplicationController
  def index
    @shop_genre = ShopGenre.new
    @shop_genres = ShopGenre.page(params[:page]).reverse_order
  end

  def create
    @shop_genre = ShopGenre.new(shop_genre_params)
    if @shop_genre.save
      redirect_to admin_shop_genres_path
    else
      @shop_genres = ShopGenre.all
      render :index
    end
  end

  def update
    @shop_genre = ShopGenre.find(params[:id])
    if @shop_genre.update(shop_genre_params)
      redirect_to admin_shop_genres_path
    else
      render :edit
    end
  end

  def destroy
    @shop_genre = ShopGenre.find(params[:id])
    @shop_genre.destroy
    redirect_to admin_shop_genres_path
  end

  def edit
    @shop_genre = ShopGenre.find(params[:id])
  end

  private

  def shop_genre_params
    params.require(:shop_genre).permit(:name)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  $tax_rate = 1.1

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!,except: [:top]


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :image, :name, :name_kana, :postal_code, :address, :telephone_number, :is_active, :point])
  end
end

app/helpers/admin/item_genres_helper.rb
module Admin::ItemGenresHelper
end

app/helpers/admin/shop_genres_helper.rb
module Admin::ShopGenresHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
       @devise_mapping ||= Devise.mappings[:user]
  end

  def TAX(price)
    @tax = ((price * $tax_rate).round(2)).ceil.to_s(:delimited)
    ("¥#{@tax}")
  end
end

app/views/admin/item_genres/edit.html.erb
<h1 class="page_title">アイテムジャンル編集</h1>

<div class="container">
  <%= form_with model: @item_genre, url: admin_item_genre_path, local: true do |f| %>
    <%= render 'parts/admin/error_message', model: f.object %>
    <div class="form-inline col-form-label-sm ml-5">
      <%= f.label :'アイテム名' %>
      <%= f.text_field :name, class:"form-control mx-4", autofocus: true %>
      <%= f.submit "変更", class:"btn btn-dark" %>
    </div>
  <% end %>
</div>

app/views/admin/item_genres/index.html.erb
<h1 class="page_title">アイテムジャンル作成</h1>

<div class="container">
  <%= form_with model: @item_genre, url: admin_item_genres_path, local: true do |f| %>
    <%= render 'parts/admin/error_message', model: f.object %>
    <div class="form-inline col-form-label-sm ml-5">
      <%= f.label :'ショップジャンル　　　' %>
      <%= f.collection_select(:shop_genre_id, @shop_genres, :id, :name, prompt: "選択して下さい", class: 'form-control') %>
    </div>
    <div class="form-inline col-form-label-sm ml-5">
      <%= f.label :'アイテムジャンル名' %>
      <%= f.text_field :name, class:"form-control mx-4", autofocus: true %>
      <%= f.submit "作成", class:"btn btn-dark" %>
    </div>
  <% end %>
</div>

<table class="table table-sm text-white w-50 mt-5">
  <% @item_genres.each do |item_genre| %>
    <tr>
      <td><%= item_genre.shop_genre.name %></td>
      <td><%= item_genre.name %></td>
      <td class="text-right">
        <%= link_to '編集', edit_admin_item_genre_path(item_genre), class:"btn btn-dark btn-sm" %>
        <%= link_to '削除', admin_item_genre_path(item_genre), method: :delete, class:"btn btn-dark btn-sm", data: {confirm: '本当に削除しますか？'} %>
      </td>
    </tr>
  <% end %>
</table>

app/views/admin/shop_genres/edit.html.erb
<h1 class="page_title">ショップジャンル編集</h1>

<div class="container">
  <%= form_with model: @shop_genre, url: admin_shop_genre_path, local: true do |f| %>
    <%= render 'parts/admin/error_message', model: f.object %>
    <div class="form-inline col-form-label-sm ml-5">
      <%= f.label :'ショップジャンル名' %>
      <%= f.text_field :name, class:"form-control mx-4", autofocus: true %>
      <%= f.submit "変更", class:"btn btn-dark" %>
    </div>
  <% end %>
</div>

app/views/admin/shop_genres/index.html.erb
<h1 class="page_title">ショップジャンル作成</h1>

<div class="container">
  <%= form_with model: @shop_genre, url: admin_shop_genres_path, local: true do |f| %>
    <%= render 'parts/admin/error_message', model: f.object %>
    <div class="form-inline col-form-label-sm ml-5">
      <%= f.label :'ショップジャンル名' %>
      <%= f.text_field :name, class:"form-control mx-4", autofocus: true %>
      <%= f.submit "作成", class:"btn btn-dark" %>
    </div>
  <% end %>
</div>

<table class="table table-sm text-white w-50 mt-5">
  <% @shop_genres.each do |shop_genre| %>
    <tr>
      <td><%= shop_genre.name %></td>
      <td class="text-right">
        <%= link_to '編集', edit_admin_shop_genre_path(shop_genre), class:"btn btn-dark btn-sm" %>
        <%= link_to '削除', admin_shop_genre_path(shop_genre), method: :delete, class:"btn btn-dark btn-sm", data: {confirm: '本当に削除しますか？'} %>
      </td>
    </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FreeMall</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="d-flex">
    <% if admin_signed_in? %>
      <%= render'parts/admin/sidebar' %>
      <main class="bg-secondary w-100 text-white">
        <%= yield %>
      </main>
    <% else %>
      <%= render'parts/user/sidebar' %>
      <div class="w-100">
        <%= render'parts/user/header' %>
        <main>
          <%= yield %>
        </main>
      </div>
    <% end %>
  </body>
</html>

app/views/parts/_sidebar.html.erb
<div class="bg-white text-left pl-5 side_bar">
  <nav class="h-100">
    <ul class="h-100 d-flex flex-column px-3">
      <li class="m-2">
        <%= link_to root_path do %>
          <%= image_tag 'logo.jpg', size:"80x80" %>
        <% end %>
      </li>
      <li><%= link_to 'Home', root_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to 'Address', addresses_path %></li>
        <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <li class="mt-auto text-center">
          <%= link_to users_path do %>
            <%= attachment_image_tag @user, :image, fallback: "toppu.png", size: "60x60", class:"rounded-circle" %>
          <% end %>
        </li>
      <% else %>
        <li class="mt-auto text-center"><%= link_to 'Sign In', user_session_path, class:"btn btn-primary w-100 mb-3" %></li>
        <li class="text-center"><%= link_to 'Sign Up', new_user_registration_path, class:"btn btn-success w-100 mb-3" %></li>
      <% end %>
    </ul>
  </nav>
</div>

app/views/parts/admin/_error_message.html.erb
<% if model.errors.any? %>
  <div class = "alert alert-light w-75">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/parts/admin/_sidebar.html.erb
<div class="bg-white text-center pl-5 side_bar w-25">
  <nav class="vh-100">
    <ul class="vh-100 d-flex flex-column px-3">
      <h4 class="text-center mt-2 bg-secondary text-white border border-dark">管理ページ</h4>
      <li class="mb-1"><%= link_to "ショップジャンル", admin_shop_genres_path, class:"border border-dark" %></li>
      <li class="mb-1"><%= link_to "アイテムジャンル", admin_item_genres_path, class:"border border-dark" %></li>
      <li class="mt-auto text-center mb-2"><%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class:"btn btn-dark" %></li>
    </ul>
  </nav>
</div>

app/views/parts/user/_error_message.html.erb
<% if model.errors.any? %>
  <div class = "alert alert-danger w-75">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/parts/user/_header.html.erb
<header class="bg-white sticky-top">
  <nav class="py-4 navbar navbar-dark bg-dark">
    <ul class="d-flex">
      <li><%= link_to "・New Shops", shops_path, class:"text-white mr-3" %></li>
      <li><%= link_to "・New Items", items_path, class:"text-white mr-3" %></li>
    </ul>
  </nav>
</header>

app/views/parts/user/_like.html.erb
<% if item.liked_by?(current_user) %>
  <span class="ml-2">
    <%= link_to item_likes_path(item), method: :delete, class:'btn-outline-danger btn-lg' do %>
      ♥<%= item.likes.count %>
    <% end %>
  </span>
  <% else %>
  <span class="ml-2">
    <%= link_to item_likes_path(item), method: :post, class:'btn-outline-danger btn-lg' do %>
      ♡<%= item.likes.count %>
    <% end %>
  </span>
<% end %>

app/views/parts/user/_notice.html.erb
<% if flash[:notice] %>
  <p class="text-danger"><%= flash[:notice] %></p>
<% end %>

app/views/parts/user/_sidebar.html.erb
<div class="bg-white text-left pl-5 side_bar">
  <nav class="vh-100">
    <ul class="vh-100 d-flex flex-column px-3">
      <li class="m-2 text-center">
        <%= link_to root_path do %>
          <%= image_tag 'logo.jpg', size:"80x80" %>
        <% end %>
      </li>
      <li><%= link_to 'Home', root_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to 'Cart', cart_items_path %></li>
        <li><%= link_to "Likes", items_path(order_sort: 1) %></li><!--item/indexで遷移元により表示するアイテムを変えたい為、リンクにパラメーターを付与-->
        <li><%= link_to 'Addresses', addresses_path %></li>
        <li class="mt-auto mb-2 text-center">
          <%= link_to users_path do %>
            <%= attachment_image_tag current_user, :image, fallback: "toppu.png", size: "60x60", class:"rounded-circle" %>
          <% end %>
        </li>
        <% if current_user.shop_active == true %>
          <li class="text-center"><%= link_to 'Create Shop', new_shop_path, class:"btn btn-success w-50 mb-2" %></li>
        <% else %>
          <li class="text-center"><%= link_to 'Create Item', new_item_path, class:"btn btn-success w-50 mb-2 btn-sm" %></li>
          <li class="text-center"><%= link_to 'My Shop', shop_path(current_user.shop.id), class:"btn btn-primary w-50 mb-2 btn-sm" %></li>
        <% end %>
        <li class="text-center"><%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:"btn btn-danger w-50 mb-2 btn-sm" %></li>

      <% else %>
        <li class="mt-auto text-center"><%= link_to 'Sign In', user_session_path, class:"btn btn-primary w-50 mb-2 btn-sm" %></li>
        <li class="text-center"><%= link_to 'Sign Up', new_user_registration_path, class:"btn btn-success w-50 mb-2 btn-sm" %></li>
      <% end %>
    </ul>
  </nav>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>